{
 "title": "Poulailler2",
 "description": "Température & Humidité dans notre poulailler",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Température",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Température",
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DHT22" }
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "alias": "Humidité",
     "measurement": "humidity",
     "query": "SELECT \"humidite\" FROM \"humidity\" WHERE (\"sensor_name\" = 'DHT22') AND $timeFilter",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DHT22" }
     ]
    }
   ]
  },
  {
   "title": "Température moyenne",
   "type": "graph",
   "description": "Température moyenne pour toutes les sondes",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "celsius", "label": "Température" }
   ],
   "targets": [
    {
     "alias": "DHT22",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DHT22" },
      { "condition": "AND", "key": "temperature", "operator": ">", "value": "-50" }
     ]
    },
    {
     "alias": "DS18B20 A1 Porte",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "289e7f193a1901a1" }
     ]
    },
    {
     "alias": "DS18B20 7A Fenêtre",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28c1ce233a19017a" }
     ]
    },
    {
     "alias": "DS18B20 88 Trappe",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "2871d30d3a190188" }
     ]
    },
    {
     "alias": "DS18B20 78 Libre",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28d52c183a190178" }
     ]
    },
    {
     "alias": "DS18B20 74 Abreuvoir",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28d79af039190174" }
     ]
    },
    {
     "alias": "DHT22 Humidty",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DHT22" },
      { "condition": "AND", "key": "humidity", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Température moyenne",
   "type": "bargauge",
   "description": "Température moyenne pour toutes les sondes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "DHT22",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DHT22" },
      { "condition": "AND", "key": "temperature", "operator": ">", "value": "-50" }
     ]
    },
    {
     "alias": "DS18B20 A1 Porte",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "289e7f193a1901a1" }
     ]
    },
    {
     "alias": "DS18B20 7A Fenêtre",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28c1ce233a19017a" }
     ]
    },
    {
     "alias": "DS18B20 88 Trappe",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "2871d30d3a190188" }
     ]
    },
    {
     "alias": "DS18B20 78 Libre",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28d52c183a190178" }
     ]
    },
    {
     "alias": "DS18B20 74 Abreuvoir",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28d79af039190174" }
     ]
    }
   ]
  },
  {
   "title": "Température moyenne",
   "type": "graph",
   "description": "Température moyenne pour toutes les sondes",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius", "label": "Température" }
   ],
   "targets": [
    {
     "alias": "DHT22",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DHT22" },
      { "condition": "AND", "key": "temperature", "operator": ">", "value": "-50" }
     ]
    },
    {
     "alias": "DS18B20 A1 Porte",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "289e7f193a1901a1" }
     ]
    },
    {
     "alias": "DS18B20 7A Fenêtre",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28c1ce233a19017a" }
     ]
    },
    {
     "alias": "DS18B20 88 Trappe",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "2871d30d3a190188" }
     ]
    },
    {
     "alias": "DS18B20 78 Libre",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28d52c183a190178" }
     ]
    },
    {
     "alias": "DS18B20 74 Abreuvoir",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor_name", "operator": "=", "value": "DS18B20" },
      { "condition": "AND", "key": "sensor_id", "operator": "=", "value": "28d79af039190174" }
     ]
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "humidity", "label": "% Humidité" }
   ],
   "targets": [
    {
     "alias": "Humidité",
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "humidity", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Humidité moyenne",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "humidity", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Autre moyens d'acceder au metriques",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "content": "# Acces au Arduino\n\n[Metriques du Arduino](http://poulailler.local)\n\n# Acces a node-red\n\n[node-red](raspberrypi4.local:1880/ui)\n\n# Camera\n\n* [Camera 1](http://192.168.81.70:8081/)\n* [Camera 2](http://192.168.81.71:8081/)\n* [Camera nocturne](rtsp://192.168.81.98/live/profile.0)"
  }
 ]
}